Repository OsamZo/goruna, pull requests merged in 2024-11, with the labels that each got.

#29 [FEAT] users 디렉토리 생성 및 Users Entity 생성
  spring/src/main/java/com/goruna/spring/common/aggregate/UserRole.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
Labels: FEAT, CHORE

#32 [FEAT] Review 엔티티 생성 작업
  spring/src/main/java/com/goruna/spring/common/aggregate/ReviewStatus.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
Labels: FEAT

#37 [FEAT] 매장 디렉토리 및 엔티티 생성
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
Labels: FEAT

#39 [FEAT] 예약 엔티티 생성
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
Labels: FEAT

#41 [CHORE] 매장 엔티티 기본 값 설정
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
Labels: CHORE

#34 [FEAT] 좋아요 엔티티 추가 작업
  spring/src/main/java/com/goruna/spring/review/entity/Good.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
Labels: FEAT

#49 [FEAT] 매장 카테고리 엔티티 생성
  spring/src/main/java/com/goruna/spring/shop/entity/ShopCategory.java
Labels: FEAT

#47 [FEAT] (사장) controller, service, repository 생성
  spring/src/main/java/com/goruna/spring/shop/controller/OwnerShopController.java
  spring/src/main/java/com/goruna/spring/shop/repository/OwnerShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FEAT

#51 [FEAT] (관리자) 매장 전체 조회 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminSearchController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminSearchResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminSearchRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminSearchService.java
Labels: FEAT

#52 [FEAT] 회원가입 구현
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/dto/SignUpRequestDTO.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepository.java
  spring/src/main/java/com/goruna/spring/users/service/UserService.java
Labels: FEAT

#55 [FEAT] 매장 카테고리 조회 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/ShopCategoryController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopCategoryReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/ShopCategory.java
  spring/src/main/java/com/goruna/spring/shop/respository/ShopCategoryRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopCategoryService.java
Labels: FEAT

#57 [FEAT] 매장 인증 전체 조회 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminAuthShopController.java
  spring/src/main/java/com/goruna/spring/shop/controller/AdminShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminAuthShopResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminShopResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminAuthShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminAuthShopService.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminShopService.java
Labels: FEAT

#58 [FEAT] 리뷰 등록 API 기능 구현
  spring/src/main/java/com/goruna/spring/book/repository/BookRepository.java
  spring/src/main/java/com/goruna/spring/common/aggregate/YnType.java
  spring/src/main/java/com/goruna/spring/review/controller/ReviewController.java
  spring/src/main/java/com/goruna/spring/review/dto/ReviewCreateRequestDTO.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepository.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FEAT, REFACTOR

#64 [CHORE] Shop 엔티티 비즈니스 이미지 url 추가
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
Labels: CHORE

#69 [REFACTOR] Controller 코드 수정
  spring/src/main/java/com/goruna/spring/shop/controller/AdminAuthShopController.java
  spring/src/main/java/com/goruna/spring/shop/controller/AdminShopController.java
Labels: REFACTOR

#66 [FEAT] 카테고리 별 매장 조회 기능 구현
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopCategoryController.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopListReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT

#72 [FEAT] 좋아요 추가 삭제 기능 구현
  spring/src/main/java/com/goruna/spring/review/controller/GoodController.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodRequestDTO.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodResponseDTO.java
  spring/src/main/java/com/goruna/spring/review/repository/GoodRepository.java
  spring/src/main/java/com/goruna/spring/review/service/GoodService.java
Labels: FEAT

#73 [FEAT] 매장 등록 인증 상세 조회 기능 구현 #70
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
  spring/src/main/java/com/goruna/spring/shop/controller/AdminAuthShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminAuthShopDetailResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminAuthShopDetailRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminAuthShopService.java
Labels: FEAT, CHORE

#78 [FEAT] 북마크 추가, 수정 작업
  spring/src/main/java/com/goruna/spring/bookmark/controller/BookmarkController.java
  spring/src/main/java/com/goruna/spring/bookmark/dto/BookmarkResponseDTO.java
  spring/src/main/java/com/goruna/spring/bookmark/entity/BookMark.java
  spring/src/main/java/com/goruna/spring/bookmark/repository/BookmarkRepository.java
  spring/src/main/java/com/goruna/spring/bookmark/service/BookmarkService.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
Labels: FEAT

#79 [REFACTOR] (관리자) 매장 등록 인증 전체 조회, 매장 전체 조회 페이징 처리
  spring/src/main/java/com/goruna/spring/shop/controller/AdminAuthShopController.java
  spring/src/main/java/com/goruna/spring/shop/controller/AdminShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminShopResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminAuthShopService.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminShopService.java
Labels: REFACTOR

#76 [FEAT] (사장) 매장 정보 수정 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/OwnerShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/UpdateShopInfoDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FEAT, CHORE

#77 [FEAT] 예약 신청 기능 구현
  spring/src/main/java/com/goruna/spring/book/controller/BookController.java
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepository.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopCategoryController.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopCategoryRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopCategoryService.java
Labels: FEAT, REFACTOR, CHORE, RENAME

#83 [FEAT] 카테고리 추가 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminCategoryController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminCategoryRequestDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminCategoryService.java
Labels: FEAT

#84 [FEAT] 매장 상세 내역 조회 기능
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopDetailReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT

#87 [CHORE] (관리자) 카테고리 등록 기능 NotBlank 어노테이션 추가
  spring/build.gradle
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminCategoryRequestDTO.java
Labels: CHORE

#89 [FEAT] 매장 등록 신청 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/ShopApplyController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopApplyReqDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopApplyService.java
Labels: FEAT

#90 [REFACTOR] 예약 생성 기능 생성자 방식 -> 빌더 패턴
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/bookmark/entity/Bookmark.java
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
Labels: REFACTOR

#93 [FEAT] (관리자) 카테고리 조회 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminCategoryController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminCategoryResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminCategoryService.java
Labels: FEAT

#95 [FEAT] 카테고리 삭제 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminCategoryController.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminCategoryService.java
Labels: FEAT

#92 [TEST] (사장) 매장 수정 기능 테스트
  spring/.gitignore
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/test/java/com/goruna/spring/shop/service/OwnerShopServiceTest.java
Labels: TEST

#96 [FEAT] security 구현
  spring/build.gradle
  spring/src/main/java/com/goruna/spring/security/SecurityConfig.java
  spring/src/main/java/com/goruna/spring/security/dto/LoginRequest.java
  spring/src/main/java/com/goruna/spring/security/filter/CustomAuthenticationFilter.java
  spring/src/main/java/com/goruna/spring/security/handler/LoginSuccessHandler.java
  spring/src/main/java/com/goruna/spring/security/util/CustomUserDetails.java
  spring/src/main/java/com/goruna/spring/security/util/CustomUserDetailsService.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepository.java
  spring/src/main/java/com/goruna/spring/users/service/UserService.java
  spring/src/main/resources/application.yml
Labels: FEAT

#100 [FEAT] 매장 사업자 등록증 조회 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminShopAuthImgDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminShopService.java
Labels: FEAT

#99 [FEAT] (사장) 매장 정보 삭제 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/OwnerShopController.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FIX, FEAT

#107 [FIX] swagger error 수정
  spring/src/main/java/com/goruna/spring/security/SecurityConfig.java
Labels: FIX

#102 [FEAT] 매장 등록 인증 수정 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminAuthShopController.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminAuthShopDetailRepository.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminAuthShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/repository/AdminShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminAuthShopService.java
Labels: FEAT, CHORE

#113 [FEAT] QueryDsl 설정 파일 추가
  spring/build.gradle
  spring/src/main/java/com/goruna/spring/config/QueryDslConfig.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminShopService.java
Labels: FEAT, CHORE

#116 fix: (사장) 내 매장 정보 조회 기능 확인용 코드 삽입
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FIX

#127 [CHORE] 프론트엔드 설정에 불필요한 코드 삭제
  frontend/src/App.vue
Labels: CHORE

#125 [FEAT] @AuthenticationPrincipal로 userSeq 가져오기
  spring/src/main/java/com/goruna/spring/security/SecurityConfig.java
  spring/src/main/java/com/goruna/spring/security/dto/ExceptionResponse.java
  spring/src/main/java/com/goruna/spring/security/dto/JwtAuthenticationEntryPoint.java
  spring/src/main/java/com/goruna/spring/security/dto/LoginRequest.java
  spring/src/main/java/com/goruna/spring/security/filter/JwtFilter.java
  spring/src/main/java/com/goruna/spring/security/handler/JwtAccessDeniedHandler.java
  spring/src/main/java/com/goruna/spring/security/handler/LoginSuccessHandler.java
  spring/src/main/java/com/goruna/spring/security/util/CustomUserDetails.java
  spring/src/main/java/com/goruna/spring/security/util/CustomUserDetailsService.java
  spring/src/main/java/com/goruna/spring/security/util/JwtUtil.java
  spring/src/main/java/com/goruna/spring/users/service/UserService.java
Labels: FEAT, CHORE

#128 [FIX] 매장, 상품 엔티티 분리
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/shop/controller/OwnerShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/CreateProductReqDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FIX, FEAT

#130 [FEAT] 리뷰 조회 API 구현
  spring/src/main/java/com/goruna/spring/review/controller/ReviewController.java
  spring/src/main/java/com/goruna/spring/review/dto/ReviewShopReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/dto/ReviewUserReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepository.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FEAT, REFACTOR

#134 [REFACTOR] 에러나는 곳 임시 주석 처리
  spring/src/main/java/com/goruna/spring/book/dto/BookListReadResDTO.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepository.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
Labels: REFACTOR

#133 [FEAT] 관리자 매장 검색 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/AdminShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/AdminShopSearchResponseDTO.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminShopService.java
Labels: FEAT

#138 [REFACTOR] 매장 추가 등록 리팩토링
  spring/src/main/java/com/goruna/spring/shop/dto/ShopApplyReqDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
Labels: REFACTOR

#139 [REFACTOR] 상품 엔티티 분리로 인한 상품 등록 기능 리펙토링
  spring/src/main/java/com/goruna/spring/product/controller/ProductController.java
  spring/src/main/java/com/goruna/spring/product/dto/CreateProductReqDTO.java
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/product/service/ProductService.java
  spring/src/main/java/com/goruna/spring/shop/controller/OwnerShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/CreateProductReqDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FIX, FEAT, REFACTOR, CHORE

#141 [CHORE] 에러나는 곳 임시 주석 처리
  spring/src/main/java/com/goruna/spring/book/controller/BookController.java
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepository.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/review/controller/ReviewController.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopDetailReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopListReadResDTO.java
Labels: FIX, CHORE

#144 [REFACTOR] 엔티티 수정으로 인한 컴파일 에러 수정
  spring/src/main/java/com/goruna/spring/review/controller/ReviewController.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: REFACTOR

#145 [FIX] 사업자 등록증 조회 에러 수정
  spring/src/main/java/com/goruna/spring/shop/service/AdminShopService.java
Labels: FIX

#147 [REFACTOR] 리뷰 조회 에러 해결
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
Labels: REFACTOR

#150 [FEAT] 관리자 리뷰 삭제 기능 구현
  spring/src/main/java/com/goruna/spring/review/controller/AdminReviewController.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
  spring/src/main/java/com/goruna/spring/review/service/AdminReviewService.java
Labels: FEAT

#153 [REFACTOR] 에러 해결 및 예약 생성 기능 리팩토링
  spring/src/main/java/com/goruna/spring/book/controller/BookController.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepository.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepository.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopDetailReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FIX, REFACTOR

#151 [FEAT] 회원 북마크 조회 기능 구현
  spring/src/main/java/com/goruna/spring/bookmark/controller/BookmarkController.java
  spring/src/main/java/com/goruna/spring/bookmark/dto/BookmarkCreatResDTO.java
  spring/src/main/java/com/goruna/spring/bookmark/dto/BookmarkReadResDTO.java
  spring/src/main/java/com/goruna/spring/bookmark/repository/BookmarkRepository.java
  spring/src/main/java/com/goruna/spring/bookmark/repository/BookmarkRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/bookmark/repository/BookmarkRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/bookmark/service/BookmarkService.java
Labels: FEAT, REFACTOR

#156 [FEAT] CustomUserUtils 구현
  spring/src/main/java/com/goruna/spring/common/util/CustomUserUtils.java
  spring/src/main/java/com/goruna/spring/security/filter/CustomAuthenticationFilter.java
  spring/src/main/java/com/goruna/spring/security/util/CustomUserDetailsService.java
  spring/src/main/java/com/goruna/spring/users/service/UserService.java
Labels: REFACTOR

#157 [REFACTOR] 에러 해결
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepository.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: REFACTOR

#162 [REFACTOR] 각 엔티티 lazy 로딩 설정 작업
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodRequestDTO.java
  spring/src/main/java/com/goruna/spring/review/entity/Good.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: REFACTOR

#165 [FIX] 좋아요 추가 안되는 이슈 해결
  spring/src/main/java/com/goruna/spring/bookmark/entity/Bookmark.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodResponseDTO.java
  spring/src/main/java/com/goruna/spring/review/entity/Good.java
  spring/src/main/java/com/goruna/spring/review/service/GoodService.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
Labels: FIX, REFACTOR

#167 [FEAT] (사장) 예약 정보 수정 기능 구현
  spring/src/main/java/com/goruna/spring/book/controller/OwnerBookController.java
  spring/src/main/java/com/goruna/spring/book/dto/UpdateBookInfoReqDTO.java
  spring/src/main/java/com/goruna/spring/book/service/OwnerBookService.java
Labels: FEAT

#168 [Feature[] Google Login Api 구현
  spring/build.gradle
  spring/src/main/java/com/goruna/spring/config/AppConfig.java
  spring/src/main/java/com/goruna/spring/security/SecurityConfig.java
  spring/src/main/java/com/goruna/spring/security/filter/JwtFilter.java
  spring/src/main/java/com/goruna/spring/security/handler/LoginSuccessHandler.java
  spring/src/main/java/com/goruna/spring/users/controller/LoginController.java
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/dto/GoogleInfResponse.java
  spring/src/main/java/com/goruna/spring/users/dto/GoogleRequest.java
  spring/src/main/java/com/goruna/spring/users/dto/GoogleResponse.java
  spring/src/main/java/com/goruna/spring/users/dto/UserRequestDto.java
  spring/src/main/java/com/goruna/spring/users/service/LoginService.java
  spring/src/main/java/com/goruna/spring/users/service/UserService.java
  spring/src/main/resources/application.yml
  spring/src/main/resources/static/favicon.ico
Labels: FEAT

#172 [FIX] 매장 리뷰 조회 안되는 이슈 해결
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/review/entity/Good.java
  spring/src/main/java/com/goruna/spring/review/entity/Review.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
  spring/src/main/resources/data.sql
Labels: FIX, FEAT, REFACTOR

#176 [FEAT] 회원 닉네임 구현
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/dto/NickNameRequestDto.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
  spring/src/main/java/com/goruna/spring/users/service/LoginService.java
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FEAT

#177 [FEAT] #132 관리자 매장 별 리뷰 조회 기능 구현
  spring/src/main/java/com/goruna/spring/review/controller/AdminReviewController.java
  spring/src/main/java/com/goruna/spring/review/dto/AdminReviewShopResDTO.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/review/repository/ReviewRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FEAT

#179 [FEAT] 프론트 의존 파일 추가
  frontend/package-lock.json
  frontend/package.json
Labels: FEAT

#180 [FEAT] 메인페이지 HTML, CSS 작업
  frontend/index.html
  frontend/src/App.vue
  frontend/src/components/test.md
  frontend/src/router/MainRouter.js
  frontend/src/router/index.js
  frontend/src/router/test.md
  frontend/src/views/main/MainPage.vue
  frontend/src/views/test.md
Labels: FEAT, CHORE

#185 [FEAT] 회원 정보 조회
  spring/src/main/java/com/goruna/spring/review/controller/ReviewController.java
  spring/src/main/java/com/goruna/spring/security/util/CustomUserDetails.java
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/dto/UserInfoResponse.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepository.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FEAT

#187 [FEAT] (사장) 내 매장 예약 목록 조회 기능 구현
  spring/src/main/java/com/goruna/spring/book/controller/OwnerBookController.java
  spring/src/main/java/com/goruna/spring/book/dto/OwnerShopBooksResDTO.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepository.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/book/service/OwnerBookService.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FEAT, CHORE

#186 [REFACTOR] reset.css 생성 및 그에 따른 수정
  frontend/index.html
  frontend/src/App.vue
  frontend/src/assets/css/reset.css
  frontend/src/components/Header.vue
  frontend/src/main.js
  frontend/src/views/main/MainPage.vue
Labels: REFACTOR, CHORE

#189 [REFACTOR] header 컴포넌트 아이디, 태그 선택자 -> 클래스 선택자
  frontend/src/components/Header.vue
  frontend/src/views/main/MainPage.vue
Labels: REFACTOR

#195 [FEAT] Review 조회에 사용되는 컴포넌트 구현 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/css/reset.css
  frontend/src/components/ShopCard.vue
  frontend/src/main.js
  frontend/src/router/MainRouter.js
  frontend/src/router/ReviewRouter.js
  frontend/src/router/index.js
  frontend/src/views/reivew/ReviewPage.vue
Labels: FEAT, REFACTOR

#196 [FEAT] 회원 매장 신청 상태 조회
  spring/src/main/java/com/goruna/spring/shop/controller/UserShopStatusController.java
  spring/src/main/java/com/goruna/spring/shop/dto/UserShopStatusResponse.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/UserShopStatusService.java
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FEAT, CHORE

#198 [FEAT] 회원 정보 수정
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/dto/UserInfoRequestDto.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FIX, FEAT

#199 [FEAT] 사장 매장 예약 수정 작업
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/book/service/OwnerBookService.java
Labels: FIX

#201 [FEAT] (사장) 예약 정보 삭제 기능 버그 수정
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
Labels: FIX

#202 [FEAT] 오늘의 특가 리스트 조회 기능 구현
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT

#207 [FIX] (사장) 상품 등록 기능 버그 수정
  spring/src/main/java/com/goruna/spring/product/dto/CreateProductReqDTO.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepository.java
  spring/src/main/java/com/goruna/spring/product/service/ProductService.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/OwnerShopRepository.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
  spring/src/test/java/com/goruna/spring/shop/service/OwnerShopServiceTest.java
Labels: FIX, CHORE

#209 [FEAT] 리뷰 페이지 퍼블리싱 완료
  frontend/src/components/ReviewList.vue
  frontend/src/components/ShopCard.vue
  frontend/src/components/WhiteContentBox.vue
  frontend/src/views/reivew/ReviewPage.vue
Labels: FEAT, REFACTOR, DESIGN

#213 [FEAT] 마이페이지 공통 템플릿
  frontend/src/assets/css/reset.css
  frontend/src/router/UserRouter.js
  frontend/src/router/index.js
  frontend/src/views/user/UserMyPage.vue
Labels: FEAT

#216 [FEAT] 지도 API 불러오기 (우선 위치는 임의로 설정)
  frontend/.gitignore
  frontend/src/views/main/MainPage.vue
Labels: FEAT

#218 [REFACTOR] 매장 승인 상태 변경으로 인한 수정
  spring/src/main/java/com/goruna/spring/common/aggregate/ShopApprStatus.java
  spring/src/main/java/com/goruna/spring/shop/controller/AdminAuthShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/UserShopStatusResponse.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/AdminAuthShopService.java
  spring/src/main/java/com/goruna/spring/shop/service/UserShopStatusService.java
Labels: REFACTOR

#219 [FEAT] 회원 정보 조회 화면
  frontend/src/views/user/UserInfo.vue
Labels: FEAT

#220 [REFACTOR] 예약 시 상품 재고 업데이트 되도록 리팩토링
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepository.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: REFACTOR, CHORE

#224 [FIX] QShop에 shopApprStatus 인식 못하는 문제 해결
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
Labels: FIX

#227 [FEAT] 로그인 화면 구현
  frontend/src/assets/css/reset.css
  frontend/src/router/UserRouter.js
  frontend/src/views/user/LoginPage.vue
Labels: FEAT

#226 [FEAT] (사장) 가장 최근 상품 조회 기능 구현
  spring/src/main/java/com/goruna/spring/product/controller/ProductController.java
  spring/src/main/java/com/goruna/spring/product/dto/CurrentProductResDTO.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/product/repository/ProductRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/product/service/ProductService.java
Labels: FEAT

#228 [FEAT] 관리자 매장 조회 페이지 구현
  frontend/src/components/AdminNav.vue
  frontend/src/components/AdminSearchBodyTitle.vue
  frontend/src/router/AdminRouter.js
  frontend/src/views/admin/AdminShopAuthSearch.vue
  frontend/src/views/admin/AdminShopSearch.vue
  spring/src/main/java/com/goruna/spring/shop/dto/AdminShopResponseDTO.java
Labels: FIX, FEAT

#231 [FEAT] 메인페이지 오늘의 특가 리스트 백엔드 연동
  frontend/src/views/main/MainPage.vue
Labels: FEAT

#232 [FEAT] (사장) 마이페이지 생성 및 라우팅 설정
  frontend/src/router/OwnerRouter.js
  frontend/src/router/index.js
  frontend/src/views/owner/OwnerMyPage.vue
Labels: FEAT

#233 [FEAT] 닉네임 설정 화면
  frontend/src/router/UserRouter.js
  frontend/src/views/user/LoginUserNickName.vue
Labels: FEAT

#237 [FEAT] (관리자) 카테고리 화면 구현
  frontend/src/components/AdminCategoryBodyTitle.vue
  frontend/src/components/AdminNav.vue
  frontend/src/router/AdminRouter.js
  frontend/src/views/admin/AdminShopAuthSearch.vue
  frontend/src/views/admin/AdminShopCategory.vue
Labels: FEAT, CHORE

#236 [FEAT] 사장 예약 내역 화면 구현
  frontend/src/main.js
  frontend/src/views/owner/OwnerBookList.vue
  frontend/src/views/owner/OwnerMyPage.vue
Labels: FEAT

#239 [FEAT] 라우터, package.json
  frontend/package.json
  frontend/src/router/OwnerRouter.js
  package.json
Labels: FEAT

#244 [FEAT] 가게 리뷰 조회 API 연동 완료
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/review/ReviewReadApi.js
  frontend/src/components/ReviewList.vue
  frontend/src/components/ShopCard.vue
  frontend/src/main.js
  frontend/src/store/ReviewStore.js
  frontend/src/store/test.md
  frontend/src/views/reivew/ReviewPage.vue
  package.json
  spring/src/main/resources/data.sql
Labels: FIX, FEAT, REFACTOR, CHORE, DESIGN

#243 [FEAT] 관리자 댓글 관리 화면 구현
  frontend/src/router/AdminRouter.js
  frontend/src/views/admin/AdminShopReview.vue
  frontend/src/views/admin/AdminShopSearch.vue
Labels: FEAT

#247 [FEAT] (사장) 매장 정보 페이지 퍼블리싱
  frontend/src/assets/css/reset.css
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/owner/ShopInfo.vue
Labels: FEAT

#249 [REFACTOR] 백엔드 리뷰 추가, 수정 리펙토링
  spring/src/main/java/com/goruna/spring/review/controller/ReviewController.java
  spring/src/main/java/com/goruna/spring/review/dto/ReviewUserReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FEAT, REFACTOR

#252 [REFACTOR] 백엔드 API 분류 작업 / 매장 리뷰 조회 / 매장 이미지, 이름 조회
  spring/src/main/java/com/goruna/spring/review/dto/ReviewShopReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/dto/ReviewUserReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopCardReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT, REFACTOR

#253 [FEAT] 리뷰 작성 페이지 퍼블리싱
  frontend/src/api/review/ReviewApi.js
  frontend/src/api/review/ReviewReadApi.js
  frontend/src/api/shop/ShopReadApi.js
  frontend/src/router/ReviewRouter.js
  frontend/src/store/ReviewStore.js
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/review/ReviewCreatePage.vue
  frontend/src/views/review/ReviewReadPage.vue
  frontend/src/views/user/UserMyPage.vue
  spring/src/main/java/com/goruna/spring/review/dto/ReviewShopReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FIX, FEAT, REFACTOR, DESIGN

#258 [FEAT] 로그인, 닉네임 설정 API 연동
  frontend/src/views/user/LoginPage.vue
  frontend/src/views/user/LoginUserNickName.vue
  spring/src/main/java/com/goruna/spring/users/controller/LoginController.java
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/service/LoginService.java
Labels: FEAT

#262 [FEAT] 매장 현재 위치 및 주위 매장 카테고리별 마커 표시
  frontend/package-lock.json
  frontend/src/views/main/MainPage.vue
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopListReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT, REFACTOR

#264 [FEAT] 북마크 페이지 퍼블리싱 완료
  frontend/src/main.js
  frontend/src/router/BookmarkRouter.js
  frontend/src/router/index.js
  frontend/src/views/bookmark/BookmarkPage.vue
  frontend/vite.config.js
Labels: FEAT

#266 [CHORE] 매장 정보 수정 기능 테스트 코드 주석 처리
  spring/src/test/java/com/goruna/spring/shop/service/OwnerShopServiceTest.java
Labels: CHORE

#269 [REFACTOR] docker 파일 수정
  spring/Dockerfile
Labels: REFACTOR

#270 [FEAT] 북마크 조회 api 연동 완료
  frontend/src/api/bookmark/bookmarkApi.js
  frontend/src/store/BookmarkStore.js
  frontend/src/views/bookmark/BookmarkPage.vue
Labels: FEAT, REFACTOR

#272 [FEAT] 매장 전체 리스트 퍼블리싱
  frontend/src/assets/css/reset.css
  frontend/src/router/ShopRouter.js
  frontend/src/router/index.js
  frontend/src/views/shop/ShopListPage.vue
Labels: DESIGN

#274 [FEAT] 북마크 삭제 api 연동 완료
  frontend/src/api/bookmark/bookmarkApi.js
  frontend/src/components/ReviewList.vue
  frontend/src/components/ShopCard.vue
  frontend/src/store/BookmarkStore.js
  frontend/src/views/bookmark/BookmarkPage.vue
  frontend/src/views/review/ReviewCreatePage.vue
  frontend/src/views/review/ReviewReadPage.vue
  spring/src/main/java/com/goruna/spring/bookmark/dto/BookmarkReadResDTO.java
  spring/src/main/java/com/goruna/spring/bookmark/service/BookmarkService.java
Labels: FEAT, REFACTOR

#277 [FEAT] front Docker 설정
  frontend/Dockerfile
  frontend/nginx.conf
Labels: FEAT

#279 [REFACTOR] 대소문자 구분
  frontend/src/views/bookmark/BookmarkPage.vue
Labels: REFACTOR

#280 [FEAT] (사장) 매장 관리(상품 등록) 페이지 퍼블리싱
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/owner/OwnerProduct.vue
  frontend/src/views/owner/ShopInfo.vue
Labels: FEAT

#281 [FEAT] 관리자 매장 사업자 등록증 상세 조회 페이지 구현
  frontend/src/components/Admin/useAuthBtn.js
  frontend/src/components/Admin/useImageModal.js
  frontend/src/components/Admin/useShopData.js
  frontend/src/router/AdminRouter.js
  frontend/src/views/admin/AdminShopAuthDetail.vue
  frontend/src/views/admin/AdminShopAuthSearch.vue
  spring/src/main/java/com/goruna/spring/shop/controller/AdminShopController.java
Labels: FIX, FEAT

#282 [FEAT] 매장 상세 조회 프론트 구현
  frontend/src/router/ShopRouter.js
  frontend/src/views/shop/ShopDetailPage.vue
  frontend/src/views/shop/ShopListPage.vue
Labels: FEAT, CHORE, DESIGN

#284 [REFACTOR] 회원가입 로직 수정
  spring/src/main/java/com/goruna/spring/users/controller/LoginController.java
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FEAT, REFACTOR

#287 [FEAT] 메인페이지 라우팅
  frontend/src/views/main/MainPage.vue
  frontend/src/views/shop/ShopListPage.vue
Labels: FEAT, REFACTOR, CHORE

#289 [FEAT] 지도 위 마커에 hover 시 매장 정보를 담은 infoWindow 띄우기 기능 구현
  frontend/src/views/main/MainPage.vue
Labels: FEAT, REFACTOR

#291 [FEAT] 예약 취소 기능 구현
  spring/src/main/java/com/goruna/spring/book/controller/BookController.java
  spring/src/main/java/com/goruna/spring/book/entity/Book.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
Labels: FEAT

#294 [REFACTOR] Admin 페이지 스크립트 분리 작업 + 피니아 Store 기능 추가
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/Admin/AuthBtnApi.js
  frontend/src/api/Admin/AuthShopDataApi.js
  frontend/src/api/Admin/CategoryApi.js
  frontend/src/api/Admin/ImageModalApi.js
  frontend/src/api/Admin/ShopAuthApi.js
  frontend/src/api/Admin/ShopReviewApi.js
  frontend/src/components/AdminCategoryBodyTitle.vue
  frontend/src/main.js
  frontend/src/store/AdminShopStore.js
  frontend/src/views/admin/AdminShopAuthDetail.vue
  frontend/src/views/admin/AdminShopAuthSearch.vue
  frontend/src/views/admin/AdminShopCategory.vue
  frontend/src/views/admin/AdminShopReview.vue
  frontend/src/views/admin/AdminShopSearch.vue
Labels: REFACTOR, CHORE

#295 [FEAT] UserStore 추가 작업
  frontend/src/api/user/UserApi.js
  frontend/src/store/UserStore.js
  frontend/src/views/bookmark/BookmarkPage.vue
  frontend/src/views/review/ReviewCreatePage.vue
  frontend/src/views/user/LoginPage.vue
  frontend/src/views/user/LoginUserNickName.vue
Labels: FEAT, REFACTOR

#297 [FEAT] 예약하기 모달 생성 및 연동
  frontend/src/views/book/BookQuantityModal.vue
  frontend/src/views/shop/ShopDetailPage.vue
  frontend/src/views/shop/ShopListPage.vue
  spring/src/main/java/com/goruna/spring/book/controller/BookController.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopDetailReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopListReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT, REFACTOR, DESIGN

#299 [FEAT] pinia 이용하여 shopSeq 저장
  frontend/src/api/shop/ShopListReadApi.js
  frontend/src/store/ShopStore.js
  frontend/src/views/main/MainPage.vue
Labels: FEAT

#300 [FEAT] (사장) 마이페이지 매장 정보 조회 api 연동
  frontend/src/api/shop/ShopReadApi.js
  frontend/src/store/ShopStore.js
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/owner/OwnerProduct.vue
  frontend/src/views/owner/ShopInfo.vue
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FIX, FEAT, CHORE

#302 [FEAT] 매장 상세 페이지 북마크 프론트 구현
  frontend/src/api/bookmark/bookmarkApi.js
  frontend/src/components/ShopCard.vue
  frontend/src/store/BookmarkStore.js
  frontend/src/views/shop/ShopDetailPage.vue
  spring/src/main/java/com/goruna/spring/bookmark/dto/BookmarkReadResDTO.java
  spring/src/main/java/com/goruna/spring/bookmark/service/BookmarkService.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopDetailReadResDTO.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT, REFACTOR, DESIGN

#305 [REFACTOR] JWT 토큰 쿠키로 담는 작업 및 리프레시 토큰 추가
  frontend/src/App.vue
  frontend/src/components/Header.vue
  frontend/src/main.js
  frontend/src/store/UserStore.js
  frontend/src/views/user/LoginUserNickName.vue
  spring/src/main/java/com/goruna/spring/security/SecurityConfig.java
  spring/src/main/java/com/goruna/spring/security/filter/JwtFilter.java
  spring/src/main/java/com/goruna/spring/security/handler/LoginSuccessHandler.java
  spring/src/main/java/com/goruna/spring/security/util/JwtUtil.java
  spring/src/main/java/com/goruna/spring/users/controller/LoginController.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
Labels: FEAT, REFACTOR

#307 [FEAT] 헤더 라우팅 설정 및 아이콘 간격 조절
  frontend/src/components/Header.vue
Labels: FEAT, REFACTOR, DESIGN

#309 [FIX] 현재 시간이 UTC로 받아와지는 문제 해결
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FIX

#311 [FEAT] 예약 수량 모달창 위치 조절 및 디자인
  frontend/src/views/shop/ShopDetailPage.vue
Labels: FEAT, DESIGN

#313 [REFACTOR] VUE에서 API 분리
  frontend/src/api/book/bookApi.js
  frontend/src/api/shop/ShopListReadApi.js
  frontend/src/api/shop/ShopReadApi.js
  frontend/src/views/book/BookQuantityModal.vue
  frontend/src/views/main/MainPage.vue
  frontend/src/views/shop/ShopDetailPage.vue
  frontend/src/views/shop/ShopListPage.vue
Labels: REFACTOR

#314 [FEAT] 좋아요 api 연동 작업 완료
  frontend/src/api/review/GoodApi.js
  frontend/src/components/ReviewList.vue
  frontend/src/store/ReviewStore.js
  frontend/src/views/review/ReviewReadPage.vue
  spring/src/main/java/com/goruna/spring/review/controller/GoodController.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodRequestDTO.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodResDTO.java
  spring/src/main/java/com/goruna/spring/review/dto/GoodResponseDTO.java
  spring/src/main/java/com/goruna/spring/review/dto/ReviewShopReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/entity/Good.java
  spring/src/main/java/com/goruna/spring/review/repository/GoodRepository.java
  spring/src/main/java/com/goruna/spring/review/service/GoodService.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FEAT, REFACTOR, DESIGN

#315 [REFACTOR] userSeq 로컬 스토리지에 저장
  frontend/src/store/UserStore.js
Labels: REFACTOR

#317 [FEAT] 정렬 및 검색 기능 구현
  frontend/src/api/shop/ShopListReadApi.js
  frontend/src/assets/css/reset.css
  frontend/src/views/book/BookQuantityModal.vue
  frontend/src/views/shop/ShopDetailPage.vue
  frontend/src/views/shop/ShopListPage.vue
  spring/src/main/java/com/goruna/spring/shop/controller/ShopController.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopService.java
Labels: FEAT, REFACTOR, CHORE

#319 [FIX] 지도에서 더보기 누를 시 다른 매장 데이터가 로드되는 문제 해결
  frontend/src/views/main/MainPage.vue
  frontend/src/views/shop/ShopDetailPage.vue
Labels: FIX

#321 [REFACTOR] userStore의 userSeq 이용하도록 리팩토링
  frontend/src/views/book/BookQuantityModal.vue
  frontend/src/views/shop/ShopDetailPage.vue
Labels: REFACTOR

#325 [REFACTOR] 중복 예약 안되도록 리팩토링
  frontend/src/api/book/bookApi.js
  frontend/src/views/book/BookQuantityModal.vue
  spring/src/main/java/com/goruna/spring/book/repository/BookRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/common/exception/ErrorCodeType.java
Labels: FEAT, REFACTOR

#323 [FEAT] 예약 시 업데이트된 재고가 화면에 표시 & 재고 0개일 경우 버튼 비활성화 기능 구현
  frontend/src/views/book/BookQuantityModal.vue
  frontend/src/views/shop/ShopDetailPage.vue
Labels: FEAT

#328 [RENAME] 파일명 수정
  frontend/src/api/admin/AuthBtnApi.js
  frontend/src/api/admin/AuthShopDataApi.js
  frontend/src/api/admin/CategoryApi.js
  frontend/src/api/admin/ImageModalApi.js
  frontend/src/api/admin/ShopAuthApi.js
  frontend/src/api/admin/ShopReviewApi.js
  frontend/src/views/admin/AdminShopAuthDetail.vue
  frontend/src/views/admin/AdminShopAuthSearch.vue
  frontend/src/views/admin/AdminShopCategory.vue
  frontend/src/views/admin/AdminShopReview.vue
Labels: RENAME

#331 [FEAT] 마이페이지 컴포넌트 생성
  frontend/src/components/MyPageBox.vue
Labels: FEAT, DESIGN

#333 [FEAT] (사장) 매장 정보 수정, 삭제 api 연동
  frontend/src/api/shop/shopApi.js
  frontend/src/store/ShopStore.js
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/owner/ReadShop.vue
  frontend/src/views/owner/ShopInfo.vue
  frontend/src/views/owner/UpdateShop.vue
  spring/src/main/java/com/goruna/spring/shop/dto/OnwerShopInfoResDTO.java
  spring/src/main/java/com/goruna/spring/shop/dto/UpdateShopInfoDTO.java
  spring/src/main/java/com/goruna/spring/shop/repository/ShopRepositoryImpl.java
Labels: FIX, FEAT, CHORE

#335 [FIX] (사장) 매장 정보 조회 기능 요청값 전달하여 처리하도록 수정
  frontend/src/api/shop/ShopReadApi.js
  frontend/src/store/ShopStore.js
  frontend/src/views/owner/OwnerMyPage.vue
  spring/src/main/java/com/goruna/spring/shop/controller/OwnerShopController.java
  spring/src/main/java/com/goruna/spring/shop/service/OwnerShopService.java
Labels: FIX

#336 [FEAT] 마이페이지 예약 내역 퍼블리싱
  frontend/src/api/book/bookApi.js
  frontend/src/api/user/UserApi.js
  frontend/src/assets/css/reset.css
  frontend/src/components/MyPageBox.vue
  frontend/src/router/UserRouter.js
  frontend/src/views/book/BookCancelModal.vue
  frontend/src/views/shop/ShopDetailPage.vue
  frontend/src/views/user/MyPageBook.vue
  spring/src/main/java/com/goruna/spring/book/dto/BookListReadResDTO.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryImpl.java
Labels: FEAT, REFACTOR, DESIGN

#340 [CHORE] (사장) 매장 정보 수정 후 조회 화면으로 이동하도록 코드 수정
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/owner/ShopInfo.vue
Labels: CHORE

#341 [FEAT] 내가 쓴 리뷰 조회 페이지 구현
  frontend/src/api/user/GetUserReviewApi.js
  frontend/src/router/UserRouter.js
  frontend/src/views/user/MyPageReview.vue
  spring/src/main/java/com/goruna/spring/review/dto/ReviewUserReadResDTO.java
  spring/src/main/java/com/goruna/spring/review/service/AdminReviewService.java
  spring/src/main/java/com/goruna/spring/review/service/ReviewService.java
Labels: FIX, FEAT, CHORE

#344 [FEAT] 마이페이지 이용내역 페이지 구현
  frontend/src/api/user/UserApi.js
  frontend/src/assets/css/reset.css
  frontend/src/router/UserRouter.js
  frontend/src/views/user/MyPageHistory.vue
  spring/src/main/java/com/goruna/spring/book/dto/BookListReadResDTO.java
  spring/src/main/java/com/goruna/spring/book/service/BookService.java
  spring/src/main/java/com/goruna/spring/users/controller/UserController.java
  spring/src/main/java/com/goruna/spring/users/dto/UserInfoResponse.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryCustom.java
  spring/src/main/java/com/goruna/spring/users/repository/UserRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FEAT, REFACTOR, DESIGN

#347 [FEAT] 리뷰 등록하기 백엔드 연동
  frontend/src/store/BookmarkStore.js
  frontend/src/store/ReviewStore.js
  frontend/src/views/review/ReviewCreatePage.vue
  frontend/src/views/user/MyPageHistory.vue
  spring/src/main/java/com/goruna/spring/users/service/UserInfoService.java
Labels: FEAT

#349 [FEAT] 사업자 등록 페이지 구현
  frontend/src/router/UserRouter.js
  frontend/src/views/user/UserShopApply.vue
  spring/src/main/java/com/goruna/spring/shop/controller/ShopApplyController.java
  spring/src/main/java/com/goruna/spring/shop/dto/ShopApplyReqDTO.java
  spring/src/main/java/com/goruna/spring/shop/entity/Shop.java
  spring/src/main/java/com/goruna/spring/shop/service/ShopApplyService.java
Labels: FIX, FEAT

#350 [FIX] 오류 고침
  frontend/src/router/UserRouter.js
Labels: FIX

#351 [FEAT] BookmarkServiceTest 구현
  spring/src/test/java/com/goruna/spring/bookmark/BookmarkServiceTest.java
Labels: FEAT, TEST

#358 [TEST] 예약 서비스 레이어 테스트 코드 구현
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/users/entity/User.java
  spring/src/test/java/com/goruna/spring/book/BookServiceTest.java
Labels: FEAT, TEST

#360 [FEAT] ReviewServiceTest 작성
  spring/src/test/java/com/goruna/spring/review/ReviewServiceTest.java
Labels: FEAT, TEST

#361 [TEST] 상품 서비스 레이어 서비스 코드 작성
  spring/build.gradle
  spring/src/test/java/com/goruna/spring/product/ProductServiceTest.java
Labels: FEAT, TEST

#363 [TEST] 매장 서비스 레이어 테스트 코드 작성
  spring/src/test/java/com/goruna/spring/shop/ShopServiceTest.java
  spring/src/test/java/com/goruna/spring/shop/service/OwnerShopServiceTest.java
  spring/src/test/resources/application.yml
Labels: FEAT, TEST

#364 [FEAT] (사장) 내 매장 예약 정보 조회 및 수령 상태 수정 api 연동
  frontend/src/api/book/BookApi.js
  frontend/src/api/book/bookApi.js
  frontend/src/api/shop/ShopApi.js
  frontend/src/store/BookStore.js
  frontend/src/store/ShopStore.js
  frontend/src/views/book/BookCancelModal.vue
  frontend/src/views/book/BookQuantityModal.vue
  frontend/src/views/owner/OwnerBookList.vue
  frontend/src/views/owner/OwnerMyPage.vue
  spring/src/main/java/com/goruna/spring/book/controller/OwnerBookController.java
  spring/src/main/java/com/goruna/spring/book/dto/OwnerShopBooksResDTO.java
  spring/src/main/java/com/goruna/spring/book/repository/BookRepositoryImpl.java
  spring/src/main/java/com/goruna/spring/book/service/OwnerBookService.java
Labels: FEAT, CHORE

#366 [FEAT] 사장 메뉴 수정 페이지 구현
  frontend/src/components/MyPageBox.vue
  frontend/src/views/owner/OwnerMyPage.vue
  frontend/src/views/owner/OwnerProduct.vue
  frontend/src/views/user/MyPageReview.vue
  spring/src/main/java/com/goruna/spring/product/controller/ProductController.java
  spring/src/main/java/com/goruna/spring/product/dto/CreateProductReqDTO.java
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
  spring/src/main/java/com/goruna/spring/product/service/ProductService.java
Labels: FIX, FEAT

#370 [FIX] 오류 해결
  spring/src/main/java/com/goruna/spring/product/entity/Product.java
Labels: FIX
